# Generated by Django 4.0.2 on 2022-03-17 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
    ]
