# Generated by Django 3.2 on 2022-08-25 02:00

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('status_group', models.CharField(choices=[('-1', 'delete'), ('0', 'active'), ('1', 'lock')], default='0', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 25, 2, 0, 52, 526799))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('is_peripheral', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('status_room', models.CharField(choices=[('-1', 'delete'), ('0', 'active'), ('1', 'lock')], default='0', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
