# Generated by Django 4.0.2 on 2022-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('room_and_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status_group',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'new'), ('1', 'active'), ('2', 'lock')],
                                   default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status_room',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'new'), ('1', 'active'), ('2', 'lock')],
                                   default='0', max_length=20),
        ),
    ]
