# Generated by Django 4.0.2 on 2022-03-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('room_and_group', '0002_alter_group_status_group_alter_room_status_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_have_peripheral_device',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_room_vip',
        ),
        migrations.AddField(
            model_name='room',
            name='is_peripheral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
