# Generated by Django 3.2.12 on 2022-03-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('room_and_group', '0003_remove_room_is_have_peripheral_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status_group',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'active'), ('1', 'lock')], default='0',
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status_room',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'active'), ('1', 'lock')], default='0',
                                   max_length=20),
        ),
    ]
