# Generated by Django 4.0.2 on 2022-11-30 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_and_group', '0004_alter_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 9, 34, 53, 161455)),
        ),
    ]
