# Generated by Django 4.0.2 on 2022-03-21 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('room_and_group', '0004_alter_group_status_group_alter_room_status_room'),
        ('room_and_group', '0004_auto_20220320_1716'),
    ]

    operations = [
    ]
