# Generated by Django 4.0.2 on 2022-05-25 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_and_group', '0005_merge_20220321_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 7, 58, 19, 201330)),
        ),
    ]
