# Generated by Django 4.0.2 on 2022-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_vip',
            field=models.CharField(choices=[('1', 'yes'), ('0', 'no')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status_user',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'new'), ('1', 'active'), ('2', 'lock')],
                                   default='0', max_length=20),
        ),
    ]
