# Generated by Django 4.0.2 on 2022-03-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_customuser_is_vip_alter_customuser_status_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'BU'), ('2', 'BOM')], max_length=20, null=True),
        ),
    ]
