# Generated by Django 3.2 on 2022-10-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_group_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_user',
            name='id',
            field=models.AutoField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
