# Generated by Django 4.0.2 on 2022-03-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'BU'), ('2', 'BOM')], max_length=20, null=True),
        ),
    ]
