# Generated by Django 4.0.2 on 2022-03-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('room_and_group', '0002_alter_group_status_group_alter_room_status_room'),
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='room_and_group.group'),
        ),
    ]
