# Generated by Django 3.2 on 2022-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_group_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_user',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
