# Generated by Django 4.0.2 on 2022-03-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgotkey',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forgotkey_timeout',
            field=models.DateTimeField(null=True),
        ),
    ]
