# Generated by Django 4.0.2 on 2022-03-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'BU'), ('2', 'BOM')], default='1', max_length=20),
        ),
    ]
