# Generated by Django 3.2 on 2022-10-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_group_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
