# Generated by Django 4.0.2 on 2022-03-14 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_customuser_role'),
        ('users', '0006_customuser_forgotkey_customuser_forgotkey_timeout'),
    ]

    operations = [
    ]
