# Generated by Django 4.0.2 on 2022-03-14 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_customuser_forgotkey_customuser_forgotkey_timeout'),
        ('users', '0007_alter_customuser_phone'),
    ]

    operations = [
    ]
