# Generated by Django 4.0.2 on 2022-03-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_merge_20220314_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
