# Generated by Django 4.0.2 on 2022-03-14 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_alter_customuser_phone'),
        ('users', '0008_alter_customuser_phone'),
    ]

    operations = [
    ]
