# Generated by Django 4.0.2 on 2022-03-14 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_merge_20220314_0254'),
        ('users', '0009_merge_20220314_1019'),
    ]

    operations = [
    ]
