# Generated by Django 4.0.2 on 2022-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_merge_20220314_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='forgotkey',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='forgotkey_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
