# Generated by Django 4.0.2 on 2022-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_alter_customuser_forgotkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
