# Generated by Django 4.0.2 on 2022-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='123456', max_length=254),
        ),
    ]
