# Generated by Django 4.0.2 on 2022-03-14 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('status',
                 models.CharField(choices=[('-1', 'delete'), ('0', 'new'), ('1', 'active'), ('2', 'lock')], default='0',
                                  max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='created_by_admin_in_booking',
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
