# Generated by Django 3.2 on 2022-10-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participant',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
