# Generated by Django 4.0.2 on 2022-03-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('room_and_group', '0003_remove_room_is_have_peripheral_device_and_more'),
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='room_and_group.room'),
        ),
    ]
