# Generated by Django 3.2 on 2022-10-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='participant',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
