# Generated by Django 4.0.2 on 2022-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['time_from']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'upcoming'), ('1', 'completed')], default='0',
                                   max_length=20),
        ),
    ]
