# Generated by Django 4.0.2 on 2022-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0005_alter_booking_options_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'new'), ('1', 'active'), ('2', 'lock')],
                                   default='0', max_length=20),
        ),
    ]
