# Generated by Django 4.0.2 on 2022-03-21 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0004_alter_booking_status'),
        ('booking', '0005_alter_booking_options_alter_booking_status'),
    ]

    operations = [
    ]
