# Generated by Django 4.0.2 on 2022-03-21 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0006_alter_booking_options_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['time_from']},
        ),
    ]
