# Generated by Django 4.0.2 on 2022-03-21 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0006_merge_20220321_0843'),
        ('booking', '0007_alter_booking_options'),
    ]

    operations = [
    ]
