# Generated by Django 3.2.12 on 2022-03-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0008_merge_20220321_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('-1', 'delete'), ('0', 'active '), ('1', 'completed')], default='0',
                                   max_length=20),
        ),
    ]
