# Generated by Django 4.0.2 on 2022-03-22 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0008_merge_20220321_1739'),
        ('booking', '0009_alter_booking_status'),
    ]

    operations = [
    ]
