# Generated by Django 4.0.2 on 2022-03-25 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0006_merge_20220321_1018'),
        ('booking', '0010_merge_20220322_0247'),
        ('booking', '0010_merge_20220322_0939'),
    ]

    operations = [
    ]
