# Generated by Django 3.2.12 on 2022-03-25 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0010_merge_20220322_0247'),
        ('booking', '0010_merge_20220322_0939'),
    ]

    operations = [
    ]
