# Generated by Django 4.0.2 on 2022-03-24 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0010_merge_20220322_0247'),
        ('booking', '0010_merge_20220322_0939'),
    ]

    operations = [
    ]
