# Generated by Django 4.0.2 on 2022-03-25 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0011_merge_20220324_0802'),
        ('booking', '0011_merge_20220325_0932'),
    ]

    operations = [
    ]
