# Generated by Django 4.0.2 on 2022-03-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_merge_20220324_0957'),
        ('booking', '0011_merge_20220325_1041'),
        ('booking', '0012_merge_20220325_0719'),
    ]

    operations = [
    ]
