# Generated by Django 3.2.12 on 2022-03-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_merge_20220325_1756'),
        ('booking', '0013_merge_20220328_0922'),
    ]

    operations = [
    ]
