# Generated by Django 4.0.2 on 2022-03-31 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_merge_20220325_1756'),
        ('booking', '0013_merge_20220328_0859'),
        ('booking', '0013_merge_20220328_0922'),
    ]

    operations = [
    ]
