# Generated by Django 4.0.2 on 2022-04-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_merge_20220331_0840'),
        ('booking', '0014_merge_20220331_0900'),
    ]

    operations = [
    ]
